### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by parkerreno** [teamdubstep/capstone-prototype#11]
Reduce contrast for reduced fatigue (all pages) - attempt to draw attention towards the center of buttons and screen

**Comment by JourneyToTheWes** [comment]
- [x] Make image buttons consistent color throughout
- [x] Disable buttons (record) that have not been implemented by giving it a grayed out look
- [x] Make "b" flats look more resemble a musical flat
- [x] Make text size responsive (esp. function buttons on PianoPage)

**Comment by parkerreno** [comment]
Disabled buttons should probably be marked with the IsEnabled XAML property

**Comment by parkerreno** [comment]
Fixed in #33
