### ISSUE TITLE
Assign Preset Key Mode

### ISSUE THREAD

**Issue by JourneyToTheWes** [teamdubstep/capstone-prototype#5]
Assign key changes to the piano page

**Comment by parkerreno** [comment]
This will require a two main parts

- [x] List of presets in the format { "1", "2", "3", … "9" } (where the numbers are the notes on each virtual key - the array must have 9 items, but can have empty entries with "")
- [x]  A new screen for selecting presents

**Comment by parkerreno** [comment]
Feature complete in [877aa94](https://github.com/teamdubstep/capstone-prototype/commit/877aa94b3c4a09ecac4758a306ce47e8239e0140)
